### ISSUE TITLE
Empty text input breaks window

### ISSUE THREAD

**Issue by gamerscomplete** [tbogdala/eweygewey#3]
I have a text box that is for showing messages. If I set it do display a empty string it breaks all the bordering and has some kind of weird effect across the window.
![selection_414](https://cloud.githubusercontent.com/assets/1914997/26042795/fca2cba4-38ec-11e7-9758-3008ba721561.png)

If I set the initial message to " " it renders correctly
![selection_415](https://cloud.githubusercontent.com/assets/1914997/26042805/09819f30-38ed-11e7-96d2-a41983e8c1bd.png)

Heres an example of where the box is
![selection_416](https://cloud.githubusercontent.com/assets/1914997/26042824/2ab9b552-38ed-11e7-9d67-f852be91fa35.png)

**Comment by tbogdala** [comment]
I remember seeing that a while ago, I'll see what I can do.

**Comment by tbogdala** [comment]
Fix merged into master for v0.3.1
